package com.homedepot.di.xd.efs.to;

import static org.junit.Assert.assertEquals;

import java.sql.Date;

import org.junit.Test;


/**
 * The class <code>LaneLoadGroupVendorTOTest</code> contains tests for the
 * class {@link <code>LaneLoadGroupVendorTO</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 2/20/15 4:09 PM
 *
 * @author 583541
 *
 * @version $Revision$
 */
public class LaneLoadGroupVendorTOTest  {

	@Test
	public void testGetAndSetForlaneLoadGrpVndrId()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		int laneLoadGrpVndrId=800;
		lto.setLaneLoadGrpVndrId(laneLoadGrpVndrId);
		assertEquals(laneLoadGrpVndrId,lto.getLaneLoadGrpVndrId());

	}
	@Test
	public void testGetAndSetForlaneLoadGrpId()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		int laneLoadGrpId=123;
		lto.setLaneLoadGrpId(laneLoadGrpId);
		assertEquals(laneLoadGrpId,lto.getLaneLoadGrpId());

	}

	@Test
	public void testGetAndSetcreatedUserId()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		String  createdUserId="SXP8562";
		lto.setCreatedUserId(createdUserId);
		assertEquals(createdUserId,lto.getCreatedUserId());

	}


	@Test
	public void testGetAndSetcreatedTs()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		Date newdate = new Date(System.currentTimeMillis());
		lto.setCreatedTs(new Date(System.currentTimeMillis()));
		assertEquals(newdate,lto.getCreatedTs());

	}


	@Test
	public void testGetAndSetlastUptdUserId()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		String  userid="SXP8562";
		lto.setLastUptdUserId(userid);
		assertEquals(userid,lto.getLastUptdUserId());

	}

	@Test
	public void testGetAndSetlastUptdTs()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		Date newdate = new Date(System.currentTimeMillis());
		lto.setLastUptdTs(newdate);
		assertEquals(newdate,lto.getLastUptdTs());

	}

	@Test
	public void testGetAndSeteffectiveBeginDate()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		Date effectiveBeginDate = new Date(System.currentTimeMillis());
		lto.setEffectiveBeginDate(effectiveBeginDate);
		assertEquals(effectiveBeginDate,lto.getEffectiveBeginDate());

	}

	@Test
	public void testGetAndSeteffectiveEndDate()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		Date effectiveEndDate = new Date(System.currentTimeMillis());
		lto.setEffectiveEndDate(effectiveEndDate);
		assertEquals(effectiveEndDate,lto.getEffectiveEndDate());

	}

	@Test
	public void testGetAndSetMvndrNbr()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		String  MvndrNbr="383625";
		lto.setMvndrNbr(MvndrNbr);
		assertEquals(MvndrNbr,lto.getMvndrNbr());

	}

	@Test
	public void testGetAndSetdepartmentNbr()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		short  departmentNbr=26;
		lto.setDepartmentNbr(departmentNbr);
		assertEquals(departmentNbr,lto.getDepartmentNbr());

	}

	@Test
	public void testGetAndSetFormerchendiseBaseCode()
	{
		LaneLoadGroupVendorTO lto = new LaneLoadGroupVendorTO();
		short  merchendiseBaseCode=1;
		lto.setMerchendiseBaseCode(merchendiseBaseCode);
		assertEquals(merchendiseBaseCode,lto.getMerchendiseBaseCode());

	}

}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.homedepot.di.xd.efs.to
 * package.sourceFolder = EngineeredFlowScheduleUI_offshore/test
 * superclassType = junit.framework.TestCase
 * testCase = LaneLoadGroupVendorTOTest
 * testClassType = com.homedepot.di.xd.supplychain.to.LaneLoadGroupVendorTO
 */